runtime:
  cache_dir: ./.cache/antora

site:
  title: Tekton Tutorial(Staging)
  url: https://redhat-scholars.github.io/tekton-tutorial-staging
  start_page: tekton-tutorial::index.adoc
content:
  sources:
    - url: git@github.com:redhat-scholars/tekton-tutorial.git
      tags: []
      branches: master
      start_path: documentation
asciidoc:
  attributes:
    tutorial-namespace: tektontutorial
    kubernetes-version: v1.20.0
    release-version: staging
    page-pagination: true
    tekton-version: v0.19.0
    triggers-version: v0.10.2
    kn-version: v0.19.1
    tekton-cli-version: 0.15.0
    cli: kubectl
    openshift-version: 4.7
    kind-version: v0.9.0
    minikube-version: v1.18.1
    tutorial-apps-revision: v1.3.0
    openshift-console-url: https://console-openshift-console.apps.example.com
    etherpad-url: http://example.com
    workshop-domain: guru.devx.red
  extensions:
    - ./lib/remote-include-processor.js
    - ./lib/tab-block.js
ui:
  bundle:
    url: https://github.com/redhat-developer-demos/rhd-tutorial-ui/releases/download/v0.1.9/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ./supplemental-ui
    - path: .nojekyll
    - path: ui.yml
      contents: 'static_files: [ .nojekyll ]'
output:
  dir: ./gh-pages
