apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: webhook-gitea-
spec:
  serviceAccountName: pipeline
  taskSpec:
    params:
      - name: GITEA_USER
        type: string
        description: Gitea admin username
        default: gitea
      - name: GITEA_PASSWORD
        type: string
        description: Gitea admin password
        default: gitea
      - name: GITEA_REPO_NAME
        type: string
        description: The Gitea Repo where to add to the webhooks
        default: tekton-tutorial-greeter
    steps:
      - name: webhook-gitea
        image: quay.io/siamaksade/python-oc
        script: |
          #!/usr/bin/env python3

          import os
          import requests 

          gitea_user = "$(params.GITEA_USER)"
          gitea_pwd = "$(params.GITEA_PASSWORD)"
          webhookURL = "http://" + os.popen('oc get httpproxy el-gitea-webhook-ingress -o template --template="{{.spec.virtualhost.fqdn}}"').read()
          giteaURL = "http://" + gitea_user + ":" + gitea_pwd + "@" +os.popen('oc get svc gitea -o template --template="{{.spec.clusterIP}}"').read() + ":3000"

          # configure webhook on tekton-tutorial-greeter
          data_webhook = '{"type": "gogs", "config": { "url": "' + webhookURL + '", "content_type": "json"}, "events": ["push"], "active": true}'
          headers = {'Content-Type': 'application/json'}
          resp = requests.post(url = giteaURL + "/api/v1/repos/" + gitea_user + "/$(params.GITEA_REPO_NAME)/hooks", 
                              headers = headers, 
                              data = data_webhook) 

          if resp.status_code != 200 and resp.status_code != 201:
            print("Error configuring the webhook (status code: {})".format(resp.status_code))
            print(resp.content)
          else:
            print("Configured webhook: " + webhookURL)
