= {title}

== Tasks
include::_attributes.adoc[]

At the end of this chapter you will be able to :

* Understand what is a https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md[Task] ?
* Understand how to clone your build resources using Task
* Understand where cloned sources reside i.e. Workspace
* Create a Task that can build the sources
* How to run a Task 
* Use the pipeline resource with TaskRun

[#tekton-task-prerequisite]
== Prerequisite

include::ROOT:partial$prereq-cli.adoc[]

include::partial$tekton-api.adoc[]

include::partial$tekton-cli.adoc[]

include::partial$tekton-nav-to-folder.adoc[]

[#tekton-tasks]

[[tekton-task-clone]]
== Clone Source Code

The following listing shows a simple Task that clones the sources using git command and lists the sources:

.List application source code
[source,yaml]
----
include::ROOT:example$source-lister.yaml[]
----

The sources are usually cloned to a standard path called `/workspace/<input.resource.name>`, in this example the input source name is `source` and hence the git clone will be done to a path called `/workspace/source`.

You can create the Task using the command as shown in the following listing:

[#task-source-lister]
[source,bash,subs="+macros,+attributes"]
----
tkn task create -n {tutorial-namespace} -f source-lister.yaml
----
copyToClipboard::task-source-lister[]

Verify that your task was created:

.Verify task
[source,bash,subs="+quotes,macros+,attributes+"]
----
$ *tkn task ls*
NAME            AGE
source-lister   37 seconds ago
----

Now you can use the `tkn` CLI tool to run the Task, you can pass the parameters and input sources to the Task via the `tkn task start <options>`.

[#run-task-source-lister]
[source,bash,subs="+macros,+attributes"]
----
tkn task start source-lister --inputresource='source=git-source'
----
copyToClipboard::run-task-source-lister[]

<1> You are mapping the git-source from the Pipeline resource to be the input source for the Task.

The command should show an output like:
[source,bash,subs="+quotes,macros+,attributes+"]
----
Taskrun started: source-lister-run-96qc4
Waiting for logs to be available...
----

[NOTE]
=====
The container images used by the steps need to be downloaded therefore the first execution of the task will take some time before it starts logging the output to the terminal.
=====

Remember a Task is running as a pod therefore you can watch your pod to see task lifecycle: Init, PodInitializing, Running, and finally Completed as seen in the following listing:

.Watch the pods
[source,bash,subs="+quotes,macros+,attributes+"]
----
$ *watch kubectl get pods*
NAME                                 READY   STATUS       AGE
source-lister-run-6xpgx-pod-c7dc67   0/2     Init:0/2     9s
...
NAME                                 READY   STATUS       AGE
source-lister-run-6kt8d-pod-67b326   0/2     Completed    41s
----

If the Task ran successfully you will notice the following logs in your terminal (lines truncated for brevity):

[source,bash]
----
Taskrun started: source-lister-run-96qc4
Waiting for logs to be available...
...
[git-source-git-source-rdr2k] {"level":"info","ts":1585065123.3817806,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
[git-source-git-source-rdr2k] {"level":"info","ts":1585065133.3997571,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
[git-source-git-source-rdr2k] {"level":"info","ts":1585065138.9021251,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/redhat-developer-demos/tekton-tutorial @ master in path /workspace/source"}
[git-source-git-source-rdr2k] {"level":"warn","ts":1585065138.902316,"logger":"fallback-logger","caller":"git/git.go:149","msg":"Unexpected error: creating symlink: symlink /tekton/home/.ssh /root/.ssh: file exists"}
[git-source-git-source-rdr2k] {"level":"info","ts":1585065138.9946759,"logger":"fallback-logger","caller":"git/git.go:130","msg":"Successfully initialized and updated submodules in path /workspace/source"}

[ls-build-sources] {"level":"info","ts":1585065132.8109465,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
[ls-build-sources] total 36
[ls-build-sources] drwxr-xr-x    3 root     root          4096 Mar 24 15:52 src
[ls-build-sources] -rw-r--r--    1 root     root          3472 Mar 24 15:52 pom.xml
[ls-build-sources] -rw-r--r--    1 root     root          6609 Mar 24 15:52 mvnw.cmd
[ls-build-sources] -rwxr-xr-x    1 root     root         10078 Mar 24 15:52 mvnw
[ls-build-sources] -rw-r--r--    1 root     root           671 Mar 24 15:52 Dockerfile.jvm
[ls-build-sources] -rw-r--r--    1 root     root           188 Mar 24 15:52 Dockerfile
----

[NOTE]
====

The logs are the consolidated logs from all the Task step containers. You can identify the source of the log i.e the step that has generated the logs using the text within the square brackets `[]` of each log line.

e.g.

Logs starting with **[ls-build-sources]** are from the container that is responsible for running the Task step i.e. `ls-build-sources`.
====

[[tekton-task-list-ws]]
== Know the workspace

In the example above, there is a log which shows the `git clone` command that cloned the application sources to the `/workspace/source` directory. The *workspace* directory is where your Task/Pipeline sources/build atrifacts will be cloned and generated. The `source` sub-path under is the directory where Tekton cloned the applicaiton sources. It is usually the name of the resources --> inputs --> Resource of type Git.

[[tekton-task-build-sources]]
== Build Sources

The following snippet shows what a Tekton Task YAML looks like:

.link:{github-repo}/{pipelines-repo}/build-app-task.yaml[build-app-task.yaml]
[source,yaml,subs="+macros,attributes+"]
----
include::ROOT:example$build-app-task.yaml[]
----

Each Task has the following:

* **name** - the unique name using which the task can be referred
* **inputs** - the inputs to the task
** **resources** - the pipeline resources that will be used in the task e.g. git-source
*** **name** - the name of the input resource using which it can be referenced and bound via <<tekton-task-run>>
*** **type** - the type of the input resource, typically the pipeline resource type
** **params** - the parameters that will be used in the task steps. Each parameter has 
*** **name** - the name of the parameter
*** **description** - the description of the parameter
*** **default** - the default value of parameter

NOTE: The <<tekton-task-run>> could override the parameter values, if no parameter value is passed then the **default** value will be used.

* **outputs** the pipeline resource that will end artifact of the task. In the above example the build will produce a container image artifact.
** **resources** - the pipeline resources that will be used in the task e.g. builtImage
*** **name** - the name of the input resource using which it can be referenced and bound via <<tekton-task-run>>
*** **type** - the type of the input resource, typically the pipeline resource type
* **steps** - One or more sub-tasks that will be executed in the defined order. The step has all the attributes like a https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#pod-v1-core[Pod spec]
* **volumes** - the task can also mount external volumes using the **volumes** attribute.

The parameters that were part of the menu:spec[inputs > params] can be used in the steps using the notation `$(<variable-name>)`.

The task `build-app` is used to build the https://github.com/redhat-developer-demos/tekton-tutorial/tree/master/apps/greeter/java/quarkus[Java application] that is part of the tutorial. As a step one(`build-sources`) the application will be built using https://apache.maven.org[Apache Maven], then the step two (`build-image`) the application artifacts a **jar** in this case will be used to built the linux container image using https://buildah.io[buildah], the https://github.com/redhat-developer-demos/tekton-tutorial/tree/master/apps/greeter/java/quarkus/Dockerfile.jvm[Dockerfile] in the sources will be used as base to build the linux container image and as part of the last step(`build-push`) the built linux container image will be pushed to the container registry.

[TIP]
=====
If you plan to do the build Task multiple times then its better to have a maven repository manager like Nexus to cache the maven artifacts for faster builds. You can deploy nexus using:

ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
[#tekton-nexus-deploy-k8s]
[source,bash,subs="+macros,attributes+"]
----
kubectl create -n {tutorial-namespace} \
  -f $TUTORIAL_HOME/apps/nexus/link:{github-repo}/apps/nexus/skaffold.yaml[app.yaml]
----
copyToClipboard::tekton-nexus-deploy-k8s[]

It might take few minutes for nexus to be deployed, you can watch the status using the command `kubectl get pods -n {tutorial-namespace} -w`.
--
OpenShift::
+
--
endif::[]
[#tekton-nexus-deploy-oc]
[source,bash,subs="+macros,attributes+"]
----
oc create -n {tutorial-namespace} \
  -f $TUTORIAL_HOME/apps/nexus/link:{github-repo}/apps/nexus/skaffold.yaml[skaffold.yaml]
----
copyToClipboard::tekton-nexus-deploy-oc[]

It might take few minutes for nexus to be deployed, you can watch the status using the command `oc get pods -n {tutorial-namespace} -w`.
ifndef::workshop[]
--
====
endif::[]
=====
 
[#tekton-task-deploy]
== Deploy a task 

The application build task could be created using the command:

ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
[#tekton-task-deploy-to-k8s]
[source,bash,subs="+macros,attributes+"]
----
kubectl create -n {tutorial-namespace} -f link:{github-repo}/{pipelines-repo}/build-app-task.yaml[build-app-task.yaml]
----
copyToClipboard::tekton-task-deploy-to-k8s[]
--
OpenShift::
+
--
endif::[]
[#tekton-task-deploy-to-oc]
[source,bash,subs="+macros,attributes+"]
----
oc create -n {tutorial-namespace} -f link:{github-repo}/{pipelines-repo}/build-app-task.yaml[build-app-task.yaml]
----
copyToClipboard::tekton-task-deploy-to-oc[]
ifndef::workshop[]
--
====
endif::[]

We will use the Tekton cli to inspect the created resources

[#tekton-inspect-task]
[source,bash,subs="+macros,attributes+"]
----
tkn task ls
----
copyToClipboard::tekton-inspect-task[]

The above command should list one Task as shown below:

[source,bash]
----
NAME        AGE
build-app   12 seconds ago
source-lister   7 minutes ago
----

[TIP]
====
* Use the command **help** `tkn task --help`
====

[#tekton-task-run]
== TaskRun

The https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md[TaskRun] is used to run a specific task independently. In the following section we will run the `build-app` task created in the previous step

Before we run the Task using TaskRun let us create the Kubernetes service account and attach the needed permissions to the service account, the following Kubernetes resource defines a service account called `pipeline` in namespace `{tutorial-namespace}` who will have administrative role within the `{tutorial-namespace}` namespace.

[tabs]
====
kubectl::
+
--
[#create-pipeline-sa]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -n {tutorial-namespace} pipeline-sa-role.yaml
----
copyToClipboard::create-pipeline-sa[]
--
oc::
+
--
Service Account *pipeline* will be created automatically by OpenShift Pipelines operator.
--
====


The application build task(`build-app`) could be run using the command:

[#tekton-taskrun-sa-to-k8s]
[source,bash,subs="+macros,attributes+"]
----
tkn task start -n {tutorial-namespace} build-app \
  --inputresource='source=git-source' \
  --outputresource='builtImage=tekton-tutorial-greeter-image'
----
copyToClipboard::tekton-taskrun-sa-to-k8s[]

We will use the Tekton cli to inspect the created resources, the previous `task start` commmand will show an output to see the logs of the run like:

[source,bash,subs="+macros,attributes+"]
----
In order to track the taskrun progress run:
tkn taskrun logs build-app-run-mwjmh -f -n tektontutorial
----

NOTE: It will take few seconds for the TaskRun to show status as `Running` as it needs to download the container images.

[TIP]
====
* Use the command **help** via `tkn taskrun --help` 
* Use `tr` as shorcut for taskrun commands e.g to list taskruns run the command `tkn tr ls`
====

To check the status of the TaskRun use the `logs` command of taskrun like:

[#tekton-taskrun-logs]
[source,bash,subs="+macros,attributes+"]
----
#list running using the command tkn tr ls
tkn tr ls
# use one task run for which you need the log from list above
tkn tr logs -f -a <task-run-name> #<1>
----
copyToClipboard::tekton-taskrun-logs[]
<1> The `-f` or `-a` allows to tail the logs from all the containers of the task. For more options run `tkn tr --help`

IMPORTANT: Each task step will be run within a container of its own.

If you see the TaskRun status as `Failed` or `Error` use the following command to check the reason for error:

[#tekton-desc-taskrun]
[source,bash,subs="+macros,attributes+"]
----
tkn taskrun describe <taskrun-name>
----
copyToClipboard::tekton-desc-taskrun[]

[#tekton-test-task-output]
=== Test Task output

Lets try running the image build using the `build-app` task:

ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
[#tekton-app-run-to-k8s]
[source,bash,subs="+macros,attributes+"]
----
kubectl run demo-greeter -n {tutorial-namespace} \
 --generator='run-pod/v1' \
 --image='dev.local/rhdevelopers/tekton-tutorial-greeter' && \
kubectl expose pod demo-greeter -n {tutorial-namespace} --port 8080 --type=NodePort
----
copyToClipboard::tekton-app-run-to-k8s[]
--
OpenShift::
+
--
endif::[]
[#tekton-app-run-to-oc]
[source,bash,subs="+macros,attributes+"]
----
oc run demo-greeter -n {tutorial-namespace} --generator='run-pod/v1' --image='dev.local/rhdevelopers/tekton-tutorial-greeter' && \
oc expose pod demo-greeter -n {tutorial-namespace} --port 8080 --type=NodePort && \
oc expose svc -n {tutorial-namespace} demo-greeter
----
copyToClipboard::tekton-app-run-to-oc[]
ifndef::workshop[]
--
====
endif::[]

Lets try checking the application:

ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
[#tekton-invoke-app-k8s]
[source,bash,subs="+macros,attributes+"]
----
SVC_URL=$(minikube ip):$(kubectl get svc -n {tutorial-namespace} demo-greeter -o yaml | yq r - 'spec.ports[0].nodePort') && \
http --body $SVC_URL
----
copyToClipboard::tekton-invoke-app-k8s[]
--
OpenShift::
+
--
endif::[]
[#tekton-invoke-app-oc]
[source,bash,subs="+macros,attributes+"]
----
SVC_URL=$(oc get routes -o yaml | yq r - 'spec.url.host' )
http --body $SVC_URL
----
copyToClipboard::tekton-invoke-app-oc[]
ifndef::workshop[]
--
====
endif::[]

The above command should show an output like **Hi  greeter => 'demo-greeter' : 1**

[#tekton-task-cleanup]
== Cleanup

ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
[#tekton-task-cleanup-k8s]
[source,bash,subs="+macros,attributes+"]
----
kubectl delete pod -n {tutorial-namespace} demo-greeter &&\
kubectl delete svc -n {tutorial-namespace} demo-greeter
----
copyToClipboard::tekton-task-cleanup-k8s[]
--
OpenShift::
+
--
endif::[]
[#tekton-task-cleanup-oc]
[source,bash,subs="+macros,attributes+"]
----
oc delete pod -n {tutorial-namespace} demo-greeter &&\
oc delete svc -n {tutorial-namespace} demo-greeter &&\
oc delete route -n {tutorial-namespace} demo-greeter
----
copyToClipboard::tekton-task-cleanup-oc[]
ifndef::workshop[]
--
====
