= {title}

== Tasks
include::_attributes.adoc[]

At the end of this chapter you will be able to :

* Understand what is a https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md[Task] ?
* Understand how to clone your build resources using Task
* Understand where cloned sources reside i.e. Workspace
* Create a Task that can build the sources
* How to run a Task
* Use the pipeline resource with TaskRun

[#tekton-task-prerequisite]
== Prerequisite

include::ROOT:partial$prereq-cli.adoc[]

include::partial$tekton-api.adoc[]

include::partial$tekton-cli.adoc[]

include::partial$tekton-nav-to-folder.adoc[]

[#tekton-tasks]
== Tekton Task

Each Task has the following:

* **name** - the unique name using which the task can be referred
* **inputs** - the inputs to the task
** **resources** - the pipeline resources that will be used in the task e.g. git-source
*** **name** - the name of the input resource using which it can be referenced and bound via <<tekton-task-run>>
*** **type** - the type of the input resource, typically the pipeline resource type
** **params** - the parameters that will be used in the task steps. Each parameter has
*** **name** - the name of the parameter
*** **description** - the description of the parameter
*** **default** - the default value of parameter

NOTE: The <<tekton-task-run>> could override the parameter values, if no parameter value is passed then the **default** value will be used.

* **outputs** the pipeline resource that will end artifact of the task. In the above example the build will produce a container image artifact.
** **resources** - the pipeline resources that will be used in the task e.g. builtImage
*** **name** - the name of the input resource using which it can be referenced and bound via <<tekton-task-run>>
*** **type** - the type of the input resource, typically the pipeline resource type
* **steps** - One or more sub-tasks that will be executed in the defined order. The step has all the attributes like a https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.14/#pod-v1-core[Pod spec]
* **volumes** - the task can also mount external volumes using the **volumes** attribute.

The parameters that were part of the menu:spec[inputs > params] can be used in the steps using the notation `$(<variable-name>)`.

[[tekton-task-clone]]
== Clone Source Code

The following listing shows a simple Task that clones the sources using git command and lists the sources:

.List application source code
[source,yaml]
----
include::ROOT:example$source-lister.yaml[]
----

The sources are usually cloned to a standard path called `/workspace/<input.resource.name>`, in this example the input source name is `source` and hence the git clone will be done to a path called `/workspace/source`.

You can create the Task using the command as shown in the following listing:

[#task-source-lister]
[source,bash,subs="+macros,+attributes"]
----
tkn task create -n {tutorial-namespace} -f source-lister.yaml
----
copyToClipboard::task-source-lister[]

Verify that your task was created:

.Verify task
[source,bash,subs="+quotes,macros+,attributes+"]
----
$ *tkn task ls*
NAME            AGE
source-lister   37 seconds ago
----

Now you can use the `tkn` CLI tool to run the Task, you can pass the parameters and input sources to the Task via the `tkn task start <options>`.

[#run-task-source-lister]
[source,bash,subs="+macros,+attributes"]
----
tkn task start source-lister --inputresource='source=git-source' #<1>
----
copyToClipboard::run-task-source-lister[]

<1> You are mapping the git-source from the Pipeline resource to be the input source for the Task.

The command should show an output like:
[source,bash,subs="+quotes,macros+,attributes+"]
----
Taskrun started: source-lister-run-96qc4
Waiting for logs to be available...
----

[NOTE]
=====
The container images used by the steps need to be downloaded therefore the first execution of the task will take some time before it starts logging the output to the terminal.
=====

Remember a Task is running as a pod therefore you can watch your pod to see task lifecycle: Init, PodInitializing, Running, and finally Completed as seen in the following listing:

.Watch the pods
[source,bash,subs="+quotes,macros+,attributes+"]
----
$ *watch kubectl get pods*
NAME                                 READY   STATUS       AGE
source-lister-run-6xpgx-pod-c7dc67   0/2     Init:0/2     9s
...
NAME                                 READY   STATUS       AGE
source-lister-run-6kt8d-pod-67b326   0/2     Completed    41s
----

If the Task ran successfully you will notice the following logs in your terminal (lines truncated for brevity):

[source,bash]
----
Taskrun started: source-lister-run-96qc4
Waiting for logs to be available...
...
[git-source-git-source-rdr2k] {"level":"info","ts":1585065123.3817806,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
[git-source-git-source-rdr2k] {"level":"info","ts":1585065133.3997571,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/refs/heads/master: no such file or directory"}
[git-source-git-source-rdr2k] {"level":"info","ts":1585065138.9021251,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/redhat-developer-demos/tekton-tutorial @ master in path /workspace/source"}
[git-source-git-source-rdr2k] {"level":"warn","ts":1585065138.902316,"logger":"fallback-logger","caller":"git/git.go:149","msg":"Unexpected error: creating symlink: symlink /tekton/home/.ssh /root/.ssh: file exists"}
[git-source-git-source-rdr2k] {"level":"info","ts":1585065138.9946759,"logger":"fallback-logger","caller":"git/git.go:130","msg":"Successfully initialized and updated submodules in path /workspace/source"}

[ls-build-sources] {"level":"info","ts":1585065132.8109465,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"KO_DATA_PATH\" does not exist or is empty"}
[ls-build-sources] total 36
[ls-build-sources] drwxr-xr-x    3 root     root          4096 Mar 24 15:52 src
[ls-build-sources] -rw-r--r--    1 root     root          3472 Mar 24 15:52 pom.xml
[ls-build-sources] -rw-r--r--    1 root     root          6609 Mar 24 15:52 mvnw.cmd
[ls-build-sources] -rwxr-xr-x    1 root     root         10078 Mar 24 15:52 mvnw
[ls-build-sources] -rw-r--r--    1 root     root           671 Mar 24 15:52 Dockerfile.jvm
[ls-build-sources] -rw-r--r--    1 root     root           188 Mar 24 15:52 Dockerfile
----

[NOTE]
====

The logs are the consolidated logs from all the Task step containers. You can identify the source of the log i.e the step that has generated the logs using the text within the square brackets `[]` of each log line.

e.g.

Logs starting with **[ls-build-sources]** are from the container that is responsible for running the Task step i.e. `ls-build-sources`.
====

[[tekton-task-list-ws]]
== Know the workspace

In the example above, there is a log which shows the `git clone` command that cloned the application sources to the `/workspace/source` directory. The *workspace* directory is where your Task/Pipeline sources/build atrifacts will be cloned and generated. The `source` sub-path under is the directory where Tekton cloned the applicaiton sources. It is usually the name of the resources --> inputs --> Resource of type Git.

[[tekton-task-build-sources]]
== Build Cloud Native Application

The Tekton Task can be of one or more steps. A Cloud Native Java Application at minimum comprises of the following steps:

1. Building the Application from sources using build tool like https://maven.apache.org[Apache Maven] or https://gradle.org[Gradle]
2. Building the linux container image from the build artifacts
3. Pushing the built container image to remote registry like https://quay.io[Quay.io] or https://hub.docker.com[Docker Hub]

The task `build-app` is used to build the https://github.com/redhat-developer-demos/tekton-tutorial/tree/master/apps/greeter/java/quarkus[Java application] that is part of the tutorial. As a step one(`build-sources`) the application will be built using https://apache.maven.org[Apache Maven], then the step two (`build-image`) the application artifacts a **jar** in this case will be used to built the linux container image using https://buildah.io[buildah], the https://github.com/redhat-developer-demos/tekton-tutorial/tree/master/apps/greeter/java/quarkus/Dockerfile.jvm[Dockerfile] in the sources will be used as base to build the linux container image and as part of the last step(`build-push`) the built linux container image will be pushed to the container registry.

The following section explains the three Task steps. The <<tekton-task-deploy>> will finally deploy all these three steps together as one single `build-app` task.

[[task-parameters]]
=== Step :: Task Inputs and Outputs
.link:{github-repo}/{pipelines-repo}/build-app-task.yaml[task inputs and outputs]
[source,yaml,subs="+macros,attributes+"]
----
inputs:
    resources: #<.>
      - name: source
        type: git
    params:
      - name: contextDir #<.>
        description: the context dir within source
        default: .
      - name: destinationImage #<.>
        description: the fully qualified image name
        default: "$(outputs.resources.builtImage.url)"
      - name: dockerFile #<.>
        description: the docker file to used for building the application
        default: Dockerfile
      - name: tlsVerify #<.>
        description: tls verify
        type: string
        default: "false"
outputs:
  resources: #<.>
    - name: builtImage
      type: image
----

<.> The input referred via `source`, which will be of type `git`. Having a input resource of type `git` will cause the TektonPipelines to add implict git clone step to download the sources to `workspace/source` directory
<.> `contextDir` - specifies the directory under the sources, which will be the context for the Task
<.> `destinationImage` - the linux container image name that will be built as part of this Task. Defaults to the `outputs.resources.builtImage.url`
<.> `dockerFile` - the Dockerfile that will be used to build the image
<.> `tlsVerify` - enable or disable TLS when pushing the image to remote registry
<.> The output specifices the final output of the Task, in this case the built linux container image referred via `builtImage`

[NOTE]
====
For Task inputs and outputs - we will use the xref:pipeline-resources.adoc#tkn-see-what-you-have-deployed[PipelineResources] that was created in previous chapter.
====

[[build-sources]]
=== Step 1 :: Build Application Sources
.link:{github-repo}/{pipelines-repo}/build-app-task.yaml#L32-L43[step-build-sources]
[source,yaml,subs="+macros,attributes+"]
----
- name: build-sources
  image: docker.io/maven:3.6.3-jdk-8-slim
  workingDir: "/workspace/source/$(inputs.params.contextDir)" #<.>
  command: #<.>
    - mvn
  args: #<.>
    - -DskipTests
    - clean
    - package
  env: #<.>
    - name: user.home
      value: /home/tekton
----

<.> the working dir or the context directory within the soruces from there the build command will be run
<.> the build command to run
<.> the build command arguments
<.> The environment variables that will be set within the step container

[[build-linux-image]]
=== Step 2 :: Build Application Linux Container Image

.link:{github-repo}/{pipelines-repo}/build-app-task.yaml#L44-L62[step-build-image]
[source,yaml,subs="+macros,attributes+"]
----
- name: build-image
  image: quay.io/buildah/stable
  workingDir: "/workspace/source/$(inputs.params.contextDir)"
  command:
    - "buildah"
  args:
    - "bud"
    - "--layers"
    - "-f"
    - "$(inputs.params.dockerFile)"
    - "-t"
    - "$(inputs.params.destinationImage)"
    - "."
  securityContext: <.>
    runAsUser: 0
  volumeMounts: <.>
    - name: varlibc
      mountPath: /var/lib/containers
----
<.> Running buildah inside container needs to be run as root user and needs privilege esclation. These are set as part of security context.
<.> The buildah tool saves the built linux contianer layers in the local file system at `/var/lib/containers`, which can then be used in other <<push-linux-image,steps>> or to push the image to remote registry.

[[push-linux-image]]
=== Step 3:: Push Application Linux Container Image

.link:{github-repo}/{pipelines-repo}/build-app-task.yaml#L63-L78[step-build-image]
[source,yaml,subs="+macros,attributes+"]
----
- name: push-image
  image: quay.io/buildah/stable
  workingDir: "/workspace/source/$(inputs.params.contextDir)"
  command:
    - "buildah"
  args:
    - "push"
    - "--tls-verify=$(inputs.params.tlsVerify)"
    - $(inputs.params.destinationImage)
    - "docker://$(inputs.params.destinationImage)"
  securityContext:
    runAsUser: 0
  volumeMounts:
    - name: varlibc
      mountPath: /var/lib/containers
----

Having see the three individual steps of the `build-app` task, the following snippet shows all three chained together:

.link:{github-repo}/{pipelines-repo}/build-app-task.yaml[build-app-task.yaml]
[source,yaml,subs="+macros,attributes+"]
----
include::ROOT:example$build-app-task.yaml[]
----

[#tekton-task-deploy]
== Deploy a task

The application build task could be created using the command:

ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
[#tekton-task-deploy-to-k8s]
[source,bash,subs="+macros,attributes+"]
----
kubectl apply -n {tutorial-namespace} -f link:{github-repo}/{pipelines-repo}/build-app-task.yaml[build-app-task.yaml]
----
copyToClipboard::tekton-task-deploy-to-k8s[]
--
OpenShift::
+
--
endif::[]
[#tekton-task-deploy-to-oc]
[source,bash,subs="+macros,attributes+"]
----
oc apply -n {tutorial-namespace} -f link:{github-repo}/{pipelines-repo}/build-app-task.yaml[build-app-task.yaml]
----
copyToClipboard::tekton-task-deploy-to-oc[]
ifndef::workshop[]
--
====
endif::[]

We will use the Tekton cli to inspect the created resources

[#tekton-inspect-task]
[source,bash,subs="+macros,attributes+"]
----
tkn task ls
----
copyToClipboard::tekton-inspect-task[]

The above command should list one Task as shown below:

[source,bash]
----
NAME        AGE
build-app   12 seconds ago
source-lister   7 minutes ago
----

[TIP]
====
* Use the command **help** `tkn task --help`
====

[#tekton-task-run]
== TaskRun

The https://github.com/tektoncd/pipeline/blob/master/docs/taskruns.md[TaskRun] is used to run a specific task independently. In the following section we will run the `build-app` task created in the previous step.

The application build task(`build-app`) could be run using the command:

[#tekton-taskrun-sa-to-k8s]
[source,bash,subs="+macros,attributes+"]
----
tkn task start -n {tutorial-namespace} build-app \#<.>
  --inputresource='source=git-source' \#<.>
  --outputresource='builtImage=tekton-tutorial-greeter-image' \#<.>
  --param contextDir='apps/greeter/java/springboot' \#<.>
  --showlog#<.>
----
copyToClipboard::tekton-taskrun-sa-to-k8s[]

<.> The task that need to be run, in this case `build-app`
<.> The input resource mapping, i.e. mapping  input `source` to PipelineResource `git-source` of type `git`
<.> The output resource mapping, i.e. mapping output `builtImage` to PipelineResource `built-image` of type `image`

NOTE: It will take few seconds for the TaskRun to show status as `Running` as it needs to download the container images.

[TIP]
====
* Use the command **help** via `tkn taskrun --help`
* Use `tr` as shorcut for taskrun commands e.g to list taskruns run the command `tkn tr ls`
====

To check the status of the TaskRun use the `logs` command of taskrun like:

[#tekton-taskrun-logs]
[source,bash,subs="+macros,attributes+"]
----
#list running using the command tkn tr ls
tkn tr ls
# use one task run for which you need the log from list above
tkn tr logs -f -a <task-run-name> #<1>
----
copyToClipboard::tekton-taskrun-logs[]
<1> The `-f` or `-a` allows to tail the logs from all the containers of the task. For more options run `tkn tr --help`

Each task step will be run within a container of its own. You can list the conainers of the build pod like:

e.g. For a build pod `build-app-run-785vv-pod-6kpnb`

[tabs]
=====
kubectl::
+
--
[#step-list-containers]
[source,bash,subs="+macros,+attributes"]
----
kubectl get pod build-app-run-785vv-pod-6kpnb \
  -o jsonpath="{range .spec.containers[*] } {.name}{'\n'} {end}"
----
copyToClipboard::step-list-containers[]
--
oc::
+
--
[#step-list-containers-oc]
[source,bash,subs="+macros,+attributes"]
----
oc get pod build-app-run-785vv-pod-6kpnb \
  -o jsonpath="{range .spec.containers[*] } {.name}{'\n'} {end}"
----
copyToClipboard::step-list-containers-oc[]
--
=====

As noted from the output each container will be prefixed by `step-` followed by the step-name from the Task definition. Apart from your step pods there will also be other Tekton pods that will be added to each TaskRun.

If you see the TaskRun status as `Failed` or `Error` use the following command to check the reason for error:

[#tekton-desc-taskrun]
[source,bash,subs="+macros,attributes+"]
----
tkn taskrun describe <taskrun-name>
----
copyToClipboard::tekton-desc-taskrun[]

[#tekton-test-task-output]
=== Test Task output

Lets try running the image build using the `build-app` task:

ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
[#tekton-app-run-to-k8s]
[source,bash,subs="+macros,attributes+"]
----
kubectl run demo-greeter -n {tutorial-namespace} \
 --generator='run-pod/v1' \
 --image='example.com/rhdevelopers/tekton-tutorial-greeter' && \
kubectl expose pod demo-greeter -n {tutorial-namespace} --port 8080 --type=NodePort
----
copyToClipboard::tekton-app-run-to-k8s[]
--
OpenShift::
+
--
endif::[]
[#tekton-app-run-to-oc]
[source,bash,subs="+macros,attributes+"]
----
oc run demo-greeter -n {tutorial-namespace} --generator='run-pod/v1' --image='dev.local/rhdevelopers/tekton-tutorial-greeter' && \
oc expose pod demo-greeter -n {tutorial-namespace} --port 8080 --type=NodePort && \
oc expose svc -n {tutorial-namespace} demo-greeter
----
copyToClipboard::tekton-app-run-to-oc[]
ifndef::workshop[]
--
====
endif::[]

Wait for the `demo-greeter` to be up and running:

[tabs]
====
kubectl::
+
--
watch kubectl get pods -n {tutorial-namespace}
--
oc::
+
--
watch oc get pods -n {tutorial-namespace}
--
====

Lets try checking the application:

ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
[#tekton-invoke-app-k8s]
[source,bash,subs="+macros,attributes+"]
----
SVC_URL=$(minikube -p {tutorial-namespace} -n {tutorial-namespace} service demo-greeter --url) && \
http --body $SVC_URL
----
copyToClipboard::tekton-invoke-app-k8s[]
--
OpenShift::
+
--
endif::[]
[#tekton-invoke-app-oc]
[source,bash,subs="+macros,attributes+"]
----
SVC_URL=$(oc get routes -o yaml | yq r - 'spec.url.host' )
http --body $SVC_URL
----
copyToClipboard::tekton-invoke-app-oc[]
ifndef::workshop[]
--
====
endif::[]

The above command should show an output like **hello**

[[tekton-task-step-template]]
== Step Template

When there is a need to have similar container configuration across all steps of a Task, we can have them defined in the stepTemplate. The Task steps will then inherit them implicitly in all steps. In the example above we define the resources and securityContext for all the steps using the stepTemplate.  Also if you notice in the example above we can also override the stepTemplate at the step level. That gives a unique flexibility to tweak the settings at step level.

With the current `build-app` task, we see the following configurations are repeated in `build-image` and `push-image`:

[source,yaml]
----
securityContext:
  privileged: true
  runAsUser: 0
volumeMounts:
  - name: varlibc
    mountPath: /var/lib/containers
----

We can move the the above step configuration into a stepTemplate as shown in the following updated `build-app` task:

[source,yaml]
----
include::ROOT:example$build-app-task-step-template.yaml[]
----

Now you can apply the task as shown:

[tabs]
====
kubectl::
+
--
[#apply-task-step-tpl]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n {tutorial-namespace} -f build-app-task-step-template.yaml
----
copyToClipboard::apply-task-step-tpl[]
--
oc::
+
--
[#oc-apply-task-step-tpl]
[source,bash,subs="+macros,+attributes"]
----
oc apply -n {tutorial-namespace} -f build-app-task-step-template.yaml
----
copyToClipboard::oc-apply-task-step-tpl[]
--
====

Now try <<tekton-task-run,running>> task agian. When you examine the TaskRun pods should notice `stepTemplate` added to all the step containers including `build-sources`.

Assuming the build-app-run pod to be `build-app-run-bsr4k-pod-xbxwg`:

Check `securityContext`:

[tabs]
====
kubectl::
+
--
[#check-sc]
[source,bash,subs="+macros,+attributes"]
----
kubectl get pod -n {tutorial-namespace} build-app-run-bsr4k-pod-xbxwg\
-o=jsonpath="{range .spec.containers[*]} {.name} {'\n'} {.volumeMounts[?(@.name=='varlibc')]} {'\n'} {end}"
----
copyToClipboard::apply-check-sc[]
--
oc::
+
--
[#oc-check-sc]
[source,bash,subs="+macros,+attributes"]
----
oc get pod -n {tutorial-namespace} build-app-run-bsr4k-pod-xbxwg\
-o=jsonpath="{range .spec.containers[*]} {.name} {'\n'} {.volumeMounts[?(@.name=='varlibc')]} {'\n'} {end}"
----
copyToClipboard::oc-check-sc[]
--
====

The command should an output like :

[source,bash]
----
 step-create-dir-builtimage-4jmh2
 map[privileged:true runAsUser:0]

 step-git-source-git-source-fgq4p
 map[privileged:true runAsUser:0]

 step-build-sources
 map[privileged:true runAsUser:0]

 step-build-image
 map[privileged:true runAsUser:0]

 step-push-image
 map[privileged:true runAsUser:0]

 step-image-digest-exporter-8g4ss
 map[privileged:true runAsUser:0]
----

Check `volumeMounts`:

[tabs]
====
kubectl::
+
--
[#check-vm]
[source,bash,subs="+macros,+attributes"]
----
kubectl get pod -n {tutorial-namespace} build-app-run-bsr4k-pod-xbxwg\
-o=jsonpath="{range .spec.containers[*]} {.name} {'\n'} {.volumeMounts[?(@.name=='varlibc')]} {'\n'} {end}"
----
copyToClipboard::apply-check-vm[]
--
oc::
+
--
[#oc-check-vm]
[source,bash,subs="+macros,+attributes"]
----
oc get pod -n {tutorial-namespace} build-app-run-bsr4k-pod-xbxwg\
-o=jsonpath="{range .spec.containers[*]} {.name} {'\n'} {.volumeMounts[?(@.name=='varlibc')]} {'\n'} {end}"
----
copyToClipboard::oc-check-vm[]
--
====

The command should an output like :

[source,bash]
----
step-create-dir-builtimage-4jmh2
 map[mountPath:/var/lib/containers name:varlibc]

step-git-source-git-source-fgq4p
 map[mountPath:/var/lib/containers name:varlibc]

step-build-sources
 map[mountPath:/var/lib/containers name:varlibc]

step-build-image
 map[mountPath:/var/lib/containers name:varlibc]

step-push-image
 map[mountPath:/var/lib/containers name:varlibc]

step-image-digest-exporter-8g4ss
 map[mountPath:/var/lib/containers name:varlibc]
----

NOTE: The Task steps can override the stepTemplate values.

[#tekton-task-cleanup]
== Cleanup

ifndef::workshop[]
[tabs]
====
Kubernetes::
+
--
[#tekton-task-cleanup-k8s]
[source,bash,subs="+macros,attributes+"]
----
kubectl delete pod -n {tutorial-namespace} demo-greeter &&\
kubectl delete svc -n {tutorial-namespace} demo-greeter
----
copyToClipboard::tekton-task-cleanup-k8s[]
--
OpenShift::
+
--
endif::[]
[#tekton-task-cleanup-oc]
[source,bash,subs="+macros,attributes+"]
----
oc delete pod -n {tutorial-namespace} demo-greeter &&\
oc delete svc -n {tutorial-namespace} demo-greeter &&\
oc delete route -n {tutorial-namespace} demo-greeter
----
copyToClipboard::tekton-task-cleanup-oc[]
ifndef::workshop[]
--
====
