At the end of this chapter you will be able to :

* Understand what is a https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md[Pipeline] ?
* Add Tasks from Catalog
* Create a Pipeline
* Execute a Pipeline to build and deploy a Knative service 

include::partial$tekton-nav-to-folder.adoc[tags="folder-all,pipelines"]

Ensure the Tasks are available:
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
tkn task ls 
----

The command should show a output like:

[.console-output]
[source,bash]
----
NAME            DESCRIPTION   AGE
build-app                     20 minutes ago
source-lister                 22 minutes ago
----

If you don't see the output as above please ensure you have completed all the exercises of xref::pipeline-resources.adoc[Chapter 2] and xref::tasks.adoc[Chapter 3] before proceeding further.

[#tekton-add-tasks]
== Add Tasks from catalog

The Tekton Pipelines catalog allows you to reuse the catalog from community repositories. Here is list of repositories which from where you can add tasks:

* https://github.com/tektoncd/catalog[Tekton Pipelines Catalog]
* https://github.com/openshift/pipelines-catalog[OpenShift Pipelines Catalog]

Since there is no `kubectl` task available in https://github.com/tektoncd/catalog[Tekton Pipelines Catalog] repository, we can use the OpenShift client task to deploy the app:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kubectl create -n {tutorial-namespace} \
  -f https://raw.githubusercontent.com/tektoncd/catalog/master/task/openshift-client/0.1/openshift-client.yaml
----

Check the created tasks using the command:

[.console-input]
[source,bash]
----
tkn task ls
----

The Task list should now list the following two Tasks:

[.console-output]
[source,bash,subs="+macros,attributes+"]
----
NAME               DESCRIPTION              AGE
build-app                                   21 minutes ago
openshift-client   This task runs comm...   6 seconds ago
source-lister                               23 minutes ago
----

[#tekton-pipeline-create]
== Create a Pipeline

Using a Pipeline we can run multiple Task together in a user defined sequence or order.

Let us use the `build-app` task that we created in xref:03-tasks.adoc.adoc#tekton-task-create[previous chapter] and `openshift-client` task that we deployed in previous step to make Pipeline that will build the application from sources and deploy the built linux container image.

The following snippet shows what a Tekton Pipeline YAML looks like:

.link:{github-repo}/{pipelines-repo}/svc-deploy.yaml[svc-deploy.yaml]
[source,yaml,subs="+macros,attributes+"]
----
include::ROOT:example$svc-deploy.yaml[]
----

Each Pipeline has the following:

* **name** - the unique name using which the Pipeline can be referred
* **params** - the pipeline params that will be used in the Pipeline e.g. contextDir, destinationImage
* **workspaces** - the workspaces shared by the tasks in the Pipeline.
* **tasks** - one or more Tasks that needs to be executed as part of the Pipeline

In this example we have two Tasks `build-java-app` and `deploy-kubernetes-service` that will be run to build the application from sources and deploy the built linux container image as kubernetes service.

By default all Tasks of the Pipeline runs in parallel, you can control the execution via `runAfter` attribute. In this example we make the `deploy-kubernetes-service` to run after the `build-java-app`.

Each Task in the Pipeline has 

** **taskRef** - the reference to an existing defined task via `name`
** **params** - the Task parameters to define or override
*** **name** - the name of the parameter
*** **value** - the value of the parameter

In this demo the `build-app` Task needs bind two resources namely `source` and `builtImage`. The Pipeline `deploy-kubernetes-service` defines two resources `appSource` and `appImage` that can be configured via <<tekton-pipeline-run>>. 

The binding between the Pipeline resource and Task resources is done via the task's `resources` attribute. In this demo we bind `appSource` -> `source` and `appImage` -> `builtImage`.

IMPORTANT: Only pipeline resources of same type can be bound. e.g. resource of type `git` with `git` or `image` with `image`

[#tekton-pipeline-deploy]
== Deploy Pipeline

The Kubernetes service deployment Pipeline could be created using the command:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kubectl apply -n {tutorial-namespace} -f link:{github-repo}/{pipelines-repo}/svc-deploy.yaml[svc-deploy.yaml^]
----

We will use the Tekton cli to inspect the created resources

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
tkn pipeline ls
----

The above command should list one Pipeline as shown below:

[.console-output]
[source,bash]
----
NAME            AGE             LAST RUN   STARTED   DURATION   STATUS
svc-deploy   4 seconds ago   ---        ---       ---        ---
----

[TIP]
====
Use the command **help** via `tkn pipeline --help` to see more options
====

[#tekton-pipeline-run]
== Run Pipeline

A Kubernetes Service Account is required to deploy applications in to a Kubernetes namespace. The following resource defines a service account called `pipeline` in namespace `{tutorial-namespace}`, which will have needed permissions in the `{tutorial-namespace}` namespace to perform Tekton tasks.

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n {tutorial-namespace} -f +$TUTORIAL_HOME/kubernetes/pipeline-sa-role.yaml+
----

NOTE: OpenShift Pipelines creates and uses the `pipeline` SA by default.


Run the following command to start the pipeline:

[tabs]
====
Minikube::
+
--
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
tkn pipeline start -n {tutorial-namespace} svc-deploy \
  --param contextDir='springboot' \#<.>
  --param destinationImage='example.com/rhdevelopers/tekton-tutorial-greeter' \#<.>
  --serviceaccount='pipeline' \#<.>
  --showlog #<.>
----
--
OpenShift::
+
--
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
tkn pipeline start -n {tutorial-namespace} svc-deploy \
  --param contextDir='springboot' \#<.>
  --param destinationImage='image-registry.openshift-image-registry.svc:5000/tektontutorial/tekton-tutorial-greeter'\ #<.>
  #--serviceaccount='pipeline' \#<.>
  --showlog#<.>
----
--
====

<.> Bind the Pipeline `contextDir` to context directory from where to build the application.
<.> Bind the Pipeline `destinationImage` to a specified value.
<.> The service account to use with Pipeline run. This is needed only for Minikube.
<.> Show the logs when running the pipeline.

It will take few seconds for the PipelineRun to show status as `Running` as it needs to download the container images.

[TIP]
====
* Use the command **help** via `tkn pipelinerun --help`
* Use `pr` as shorcut for pipelinerun commands e.g to list pipelinerun run the command `tkn pr ls`
====

If you see the PipelineRun status as `Failed` or `Error` use the following command to check the reason for error:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
tkn pipelinerun describe <pipelinerun-name>
----

The successful `Pipeline` run would have created a Kubernetes deployment and service called `greeter`:

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
kubectl get deploy,svc -n {tutorial-namespace} -l=app=greeter
----

[.console-output]
[source,bash]
----
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/greeter   1/1     1            1           9m31s

NAME              TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
service/greeter   NodePort   10.96.251.232   <none>        8080:31918/TCP   9m31s
----

[#tekton-test-pipeline]
== Invoke Service

Get the service URL,

[tabs]
====
Minikube::
+
--

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
SVC_URL=$(minikube -p {tutorial-namespace} -n {chapter-namespace} greeter --url)
----
--
OpenShift::
+
--
In OpenShift you can use the routes like:
[.console-input]
[source,bash,subs="+macros,attributes+"]
----
oc expose svc greeter
SVC_URL=$(oc get route greeter  -o yaml -o jsonpath='{.spec.host}')
----
--
====

Run the service,

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
http --body $SVC_URL
----

The `http` command should return a response containing a line similar to **Meeow!! from Tekton 😺🚀**

[#tekton-pipeline-cleanup]
== Cleanup

Clean the completed/failed Task and Pipeline run pods

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
$TUTORIAL_HOME/bin/cleanup.sh
----
