WARNING: This chapter build is in progress, expect to change and not working as expected

At the end of this chapter you will be able to :

* Understand what is a https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md[Workspaces] ?
* Mount ConfigMap based configurations as Workspace
* Mount a PersistenceVolume as Workspace
* Share and Cache build artifacts
* Use workspace in TaskRun
* Use workspace in PipelineRun

include::partial$tekton-nav-to-folder.adoc[tags="folder-all,workspaces"]

== Why Workspace ?

In many partical usecases of Pipelines it becomes cricual for you to share the filsystem with between Tasks and between Steps. The filesystem could be typically hold a clone github repostiory, a ConfigMap or a secret. 

Tekton `workspace` a technique by which the Task step and Pipeline task can share a common filesystem. This helps Pipelines to pick up changes form one task to another task in the Pipeline workflow.

[#ws-overview]
== Overview

As part of `workspaces` exercies, we will be building the Java application https://maven.apache.org[Apache Maven]. Using Java Application usecase allows us to explore all possible applications of workspaces:

* Mount ConfigMap based configurations as Workspace
* Mount a PersistenceVolume as Workspace
* Share and Cache build artifacts

[#ws-prepare]
== Prepare for using workspaces

include::ROOT:partial$namespace-prep.adoc[tags="*"]

[#ws-pipeline-overview]
== Java Application Pipeline

The Java Application build pipeline will,

- Git clone using `git-clone` task, the {tutorial-apps-repo} repo and build the *springboot* application
- Will use maven task, maven task require two workspaces one for source and other for maven-settings
- Build the container image using the `buildah` task and push to the internal container registry
- Finally deploy the application onto Kubernetes using `openshift-client` task

[#ws-use-pvc]
== Using PVC As Workspace

As part of this exercise we will use PersitenceVolume(PV) and PersistenceVolumeClaim(PVC) as Tekton workspace.

[#ws-use-pvc-git-clone]
=== Git Clone TaskRun

Since we will be using the same git repo for all the exercises, lets clone it. As git clone task requires https://github.com/tektoncd/catalog/blob/master/task/git-clone/0.1/git-clone.yaml#L21-L23[`output` workspace], we will attach a PersistenceVolumeClaim to it. 

Since the cluster as *default* Storage Class, just specifying the PersistenceVolumeClaim will  bind the PVC automatically to underlying storage. We will use the PVC `tekton-tutorial-sources` that we created earlier.

Let us run the `git-clone` Task with the `TaskRun` definition as shown below:

.link:{github-repo}/{workspaces-repo}/git-clone-taskrun.yaml[git-clone-taskrun^]
[source,yaml,subs="macros+,+attributes"]
----
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  genrateName: git-clone- #<.>
  labels: #<.>
    tekton.dev/task: git-clone
spec:
  taskRef:
    name: git-clone
  params: #<.>
    - name: url
      value: {tutorial-apps-repo}
    - name: revision
      value: {tutorial-apps-revision}
  workspaces: #<.>
    - name: output
      persistentVolumeClaim:
        claimName: tekton-tutorial-sources

----
<.> As its required have unqiue name for each TaskRun we use create, as that will have new names genrated using `generateName` prefix
<.> Just marking this TaskRun as part of `git-clone` Task
<.> The GitHub Url and revision to use, for more details check the https://github.com/tektoncd/catalog/blob/master/task/git-clone/0.1/[Task]
<.> Setting the workspace `output` mapped to PVC `tekton-tutorial-sources`

[tabs]
====
tkn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
tkn task start git-clone \
  --namespace={chapter-namespace} \
  --param url={tutorial-apps-repo} \
  --param revision={tutorial-apps-revision} \
  --param deleteExisting=true \
  --workspace name=output,claimName=tekton-tutorial-sources \
  --use-param-defaults \#<.>
  --showlog
----
<.> Makes the tkn CLI to use the default values from the task definiton without prompting for values

The workspaces can be PVC or ConfigMap, Secret or emptyDir. The pattern to specify them are as follows:

* PVC
** `name=my-pvc,claimName=pvc1[,subPath=dir]`

* Secret
** `name=my-secret,secret=secret-name`

* Secret
** `name=my-config,config=rpg[,item=ultimav=1]`

* emptyDir
** `name=my-empty-dir,emptyDir=""`
--
kubectl::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -n {chapter-namespace} -f git-clone-taskrun.yaml
----
--
====

It will take few minutes for the TaskRun to start.

[NOTE]
====

Watch the status of the Task run using:
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
tkn tr ls
----

include::ROOT:partial$logs-view.adoc[tags='tr']
====

You can also check the PVC is bound, as the git-clone-task output workspace is bound to it:

[.console-output]
[source,bash]
----
NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
tekton-tutorial-sources   Bound    pvc-48aa86ae-ec20-4f0c-a2d0-65d906d41bed   1Gi        RWO            standard       6s
----

A successful git-clone TaskRun will show the following output:

[.console-output]
[source,bash,subs="attributes+"]
----
[clone] + CHECKOUT_DIR=/workspace/output/
[clone] + '[[' false '==' true ]]
[clone] + test -z
[clone] + test -z
[clone] + test -z
[clone] + /ko-app/git-init -url {tutorial-apps-repo} -revision {tutorial-apps-revision} -refspec  -path /workspace/output/ '-sslVerify=true' '-submodules=true' -depth 1
[clone] {"level":"info","ts":1595778607.616774,"caller":"git/git.go:139","msg":"Successfully cloned {tutorial-apps-repo} @ 2e3336657cc1bbf22e3db183a517dcb0a62207b9 (grafted, HEAD, origin/{tutorial-apps-revision}) in path /workspace/output/"}
[clone] {"level":"info","ts":1595778607.6473103,"caller":"git/git.go:180","msg":"Successfully initialized and updated submodules in path /workspace/output/"}
[clone] + cd /workspace/output/
[clone] + git rev-parse+ tr -d '\n'
[clone]  HEAD
[clone] + RESULT_SHA=2e3336657cc1bbf22e3db183a517dcb0a62207b9
[clone] + EXIT_CODE=0
[clone] + '[' 0 '!=' 0 ]
[clone] + echo -n 2e3336657cc1bbf22e3db183a517dcb0a62207b9
----

[#ws-use-pvc-listdir-run]
=== List Directory TaskRun

As explained in the overview one of the advantages of the `workspaces` is that it can be shared, lets run a simple list-directory Task to verify the same:

.link:{github-repo}/{workspaces-repo}/list-dir-taskrun.yaml[list-dir-taskrun.yaml^]
[source,yaml,attributes]
----
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: list-directory-
  labels:
    tekton.dev/task: list-directory
spec:
  taskRef:
    name: list-directory
  workspaces: #<.>
    - name: directory
      persistentVolumeClaim:
        claimName: tekton-tutorial-sources
----
<.> Notice that we bind the same PVC to workspace `directory` parameter of the `list-directory`.

[tabs]
====
tkn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
tkn task start list-directory \
  --namespace={chapter-namespace} \
  --workspace name=directory,claimName=tekton-tutorial-sources \
  --use-param-defaults \
  --showlog
----
--
kubectl::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -n {chapter-namespace} -f list-dir-taskrun.yaml
----
[.console-output]
[source,bash]
----
taskrun.tekton.dev/list-directory-mbkvl created
----
--
include::ROOT:partial$logs-view.adoc[tags='tr']
====

If all went well the list directory should show the directory listing of {tutorial-apps-repo}.

[.console-output]
[source,bash]
----
[list-directory] total 44
[list-directory] drwxr-xr-x    3 root     root          4096 Aug 17 07:46 springboot
[list-directory] -rw-r--r--    1 root     root           515 Aug 17 07:46 settings.xml
[list-directory] drwxr-xr-x    3 root     root          4096 Aug 17 07:46 quarkus
[list-directory] -rw-r--r--    1 root     root           926 Aug 17 07:46 pom.xml
[list-directory] -rwxr-xr-x    1 root     root          6607 Aug 17 07:46 mvnw.cmd
[list-directory] -rwxr-xr-x    1 root     root         10069 Aug 17 07:46 mvnw
[list-directory] drwxr-xr-x    2 root     root          4096 Aug 17 07:46 k8s
[list-directory] -rw-r--r--    1 root     root           596 Aug 17 07:46 README.md

[show-readme] # Tekton Greeter
[show-readme]
[show-readme] Project used as part of [Tekton Tutorial](https://dn.dev/tekton-tutorial) execersies.
[show-readme]
[show-readme] The application has one simple REST api at URI `/` that says "Meeow from Tekton 😺 !! 🚀".
[show-readme]
[show-readme] ## Quarkus
[show-readme]
[show-readme] [Quarkus](./quarkus)
[show-readme]
[show-readme] ### Building locally
[show-readme]
[show-readme] ```shell
[show-readme] ./mvnw clean package -pl quarkus
[show-readme] ```
[show-readme]
[show-readme] ### Running locally
[show-readme]
[show-readme] ```shell
[show-readme] java -jar quarkus/target/quarkus-app/quarkus-run.jar
[show-readme] ```
[show-readme]
[show-readme] ## SpringBoot
[show-readme]
[show-readme] [SpringBoot](./quarkus)
[show-readme]
[show-readme] ### Building locally
[show-readme]
[show-readme] ```shell
[show-readme] ./mvnw clean package -pl springboot
[show-readme] ```
[show-readme]
[show-readme] ### Running locally
[show-readme]
[show-readme] ```shell
[show-readme] java -jar springboot/target/tekton-springboot-greeter.jar
[show-readme] ```
----

[#ws-pvc-points-to-ponder]
=== Points to Ponder

- What is a workspace
- How to bind a workspace to a TaskRun using PVC
- How to share the workaapce across multiple TaskRuns 

[#ws-use-cm]
== Using ConfigMap as Workspace

As part of this exercise we will use and configure Tekton `workspace` with ConfigMap.

[#ws-use-cm-mvn-run]
=== Run maven Task

In this exercise, we will use maven-settings ConfigMap that we created earlier as one of workspace parameter https://github.com/tektoncd/catalog/blob/master/task/maven/0.1/maven.yaml#L16[maven-settings] and for the https://github.com/tektoncd/catalog/blob/master/task/maven/0.1/maven.yaml#L15[source] workspace paramter we use the `tekton-tutorial-sources` PVC.

Let run the maven task to build the tekton-greeter project we cloned earlier.

.link:{github-repo}/{workspaces-repo}/maven-taskrun.yaml[maven-taskrun.yaml^]
[source,yaml,attributes]
----
apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: maven-build-
  labels:
    tekton.dev/task: maven
spec:
  taskRef:
    name: maven
  params:
    - name: GOALS #<.>
      value:
        - -B
        - -pl
        - springboot
        - -DskipTests
        - clean
        - package
  workspaces:
    - name: maven-settings
      configmap: #<.>
        name: maven-settings
    - name: source
      persistentVolumeClaim: #<.>
        claimName: tekton-tutorial-sources

----
<.> Specifying the maven goals to be run as a part of the build
<.> Configure the maven-settings configmap to be used for `maven-settings` workspace
<.> Configure the tekton-tutorial-sources PVC to be used for `source` workspace

[tabs]
====
tkn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
tkn task start maven \
  --namespace={chapter-namespace} \
  --param GOALS='-pl,springboot,-B,-DskipTests,clean,package' \
  --workspace name=maven-settings,config=maven-settings \
  --workspace name=source,claimName=tekton-tutorial-sources \
  --use-param-defaults \
  --showlog
----
--
kubectl::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -n {chapter-namespace} -f maven-taskrun.yaml 
----

[.console-output]
[source,bash]
----
taskrun.tekton.dev/maven-build-9cjws created
----

include::ROOT:partial$logs-view.adoc[tags='tr']
--
====


A successfull run should have output like(output trimmed for brevity):

[.console-output]
[source,bash]
----
...
[mvn-goals] [INFO] Downloaded from nexus: http://nexus:8081/repository/maven-public/org/eclipse/sisu/org.eclipse.sisu.plexus/0.3.4/org.eclipse.sisu.plexus-0.3.4.jar (205 kB at 1.0 MB/s)
[mvn-goals] [INFO] Downloaded from nexus: http://nexus:8081/repository/maven-public/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar (379 kB at 1.9 MB/s)
[mvn-goals] [INFO] Downloaded from nexus: http://nexus:8081/repository/maven-public/org/codehaus/plexus/plexus-classworlds/2.6.0/plexus-classworlds-2.6.0.jar (53 kB at 259 kB/s)
[mvn-goals] [INFO] Downloaded from nexus: http://nexus:8081/repository/maven-public/org/sonatype/plexus/plexus-build-api/0.0.7/plexus-build-api-0.0.7.jar (8.5 kB at 40 kB/s)
[mvn-goals] [INFO] Replacing main artifact with repackaged archive
[mvn-goals] [INFO] ------------------------------------------------------------------------
[mvn-goals] [INFO] BUILD SUCCESS
[mvn-goals] [INFO] ------------------------------------------------------------------------
[mvn-goals] [INFO] Total time:  8.572 s
[mvn-goals] [INFO] Finished at: 2020-08-17T08:20:22Z
[mvn-goals] [INFO] ------------------------------------------------------------------------
...
----

[NOTE]
====
When the TaskRun runs for the first , it will run loner as  it will maven artifacts for the first time and caches the artifacts nexus repository manager. Try running the command again to see it will run a lot quicker.
====

[#ws-use-cm-list-target-dir]
=== List build target directory

[tabs]
====
tkn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
tkn task start list-directory \
  --namespace={chapter-namespace} \
  --param sub-dirs='springboot/target' \
  --workspace name=directory,claimName=tekton-tutorial-sources \
  --use-param-defaults \
  --showlog
----
--
kubectl::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -n {chapter-namespace} -f link:{github-repo}/{workspaces-repo}/list-target-dir-taskrun.yaml[list-target-dir-taskrun.yaml]
----

[.console-output]
[source,bash]
----
taskrun.tekton.dev/list-directory-xbzpq created
----

include::ROOT:partial$logs-view.adoc[tags='tr']
--
====

A successful command should show the following output:

The output(trimmed for brevity) of the command should be like:

[.console-output]
[source,bash]
----
[list-directory] total 18020
[list-directory] drwxr-xr-x    3 root     root          4096 Aug 17 08:21 maven-status
[list-directory] drwxr-xr-x    3 root     root          4096 Aug 17 08:21 generated-sources
[list-directory] drwxr-xr-x    3 root     root          4096 Aug 17 08:21 test-classes
[list-directory] drwxr-xr-x    3 root     root          4096 Aug 17 08:21 generated-test-sources
[list-directory] drwxr-xr-x    3 root     root          4096 Aug 17 08:21 classes
[list-directory] -rw-r--r--    1 root     root          3748 Aug 17 08:21 tekton-springboot-greeter.jar.original
[list-directory] drwxr-xr-x    2 root     root          4096 Aug 17 08:21 maven-archiver
[list-directory] -rw-r--r--    1 root     root      18421378 Aug 17 08:21 tekton-springboot-greeter.jar
...
----

[#use-cm-points-to-ponder]
=== Points to Ponder

- How to mount a ConfigMap as workspace
- Use the workspace across TaskRuns in this case used the git-clone output in maven build using `tekton-tutorial-sources` PVC as workspace

[#ws-deploy-pipeline]
== Deploy Pipeline

Let us now apply what we learned with workspace to build and deploy the application pipeline as shown:

.link:{github-repo}/{workspaces-repo}/greeter-app-deploy.yaml[greeter-app-deploy.yaml^]
[source,yaml,subs="+macros,attributes+,quotes+"]
----
include::ROOT:example$greeter-app-deploy.yaml[]
----
<.> The parameters for the Pipeline
<.> A workpace named `source`, we will map it to the PVC`tekton-tutorial-sources`  in PipelineRun in upcoming section
<.> A workapce named `maven-settings`, we will map it to ConfigMap `maven-settings` in the PipelineRun in upcming section
<.> The `buildah` build image task returns a output, the built Image digest via https://github.com/tektoncd/catalog/blob/master/task/buildah/0.1/buildah.yaml#L53-L55[IMAGE_DIGEST]. We use the that as part of the `--image` parameter to `kn` Task

[#ws-create-pipeline]
=== Create the Pipeline

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl apply -n {chapter-namespace} -f greeter-app-deploy.yaml
----

[.console-output]
[source,bash]
----
pipeline.tekton.dev/greeter-app-deploy created
----

=== Create Service Account 

We need to create the Service Account(SA) that is authorized to Knative Service deployments. To create the SA run:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl -sSL \
  https://raw.githubusercontent.com/tektoncd/catalog/master/task/kn/0.1/support/kn-deployer.yaml \
  | yq w - -d0 metadata.namespace {chapter-namespace} \
  | yq w - -d2 subjects.[0].namespace {chapter-namespace} \
  | kubectl apply -f -
----

The successful command should show an output like:

[.console-output]
[source,bash]
----
serviceaccount/kn-deployer-account created
clusterrole.rbac.authorization.k8s.io/kn-deployer created
clusterrolebinding.rbac.authorization.k8s.io/kn-deployer-binding created
----

[#ws-run-pipeline]
=== Run the Pipeline

[tabs]
====
tkn::
+
--
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
tkn pipeline start greeter-app-deploy \
  --namespace={chapter-namespace} \
  --serviceaccount=kn-deployer-account \
  --param context-dir='quarkus' \
  --workspace name=maven-settings,config=maven-settings \
  --workspace name=source,claimName=tekton-tutorial-sources \
  --use-param-defaults \
  --showlog
----
--
kubectl::
+
--
.link:{github-repo}/{workspaces-repo}/greeter-app-deploy-run.yaml[greeter-app-deploy-run.yaml^]
[source,yaml,attributes]
----
include::ROOT:example$greeter-app-deploy-run.yaml[]
----

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl create -n {chapter-namespace} -f greeter-app-deploy-run.yaml
----

[.console-output]
[source,bash]
----
pipelinerun.tekton.dev/greeter-app-7k9cw created
----

include::ROOT:partial$logs-view.adoc[tags='pr']
--
====

A successfull Pipelinerun should have the `greeter` application up and running as shown:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kn service describe -n {chapter-namespace} greeter
----

The command should show an output like :

[.console-output]
[source,bash,subs="+quotes,attributes+"]
----
Name:       greeter
Namespace:  {chapter-namespace}
Age:        21s
#URL:        http://greeter.{chapter-namespace}.192.168.64.7.nip.io#

Revisions:
  100%  @latest (greeter-ttyqz-1) [1] (21s)
        Image:  example.com/tekton-tutorial/greeter@sha256:79b8a50a6ef29dbc0df5220de5aea13b8b38b7c4cd407ad074968de8cfbd41b6 (at 79b8a5)

Conditions:
  OK TYPE                   AGE REASON
  ++ Ready                  13s
  ++ ConfigurationsReady    14s
  ++ RoutesReady            13s
----

[#ws-verify-service]
=== Verify Deployed Service

Let us now verify the deployed Knative Service:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
KSVC_URL=$(kn service describe -n {chapter-namespace} greeter -o url)
----

Now do a invoke the service like:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
http --body +$KSVC_URL+
----

A successfull pipeline deployment should show an output like:

[.console-output]
[source,text,subs="+quotes"]
----
*Tekton 😺 rocks 🚀*
----

[#tekton-ws-cleanup]
== Cleanup

IMPORTANT: Leave the namespace, nexus, pvc, confimaps created as part of this chapter, as we will be reusing them in next chapter.

[.console-input]
[source,bash,subs="+macros,attributes+"]
----
$TUTORIAL_HOME/bin/cleanup.sh {chapter-namespace}
----

