[#start-minikube]
**Configure and Start Minikube**

Before installing Knative and its components, we need to create a Minikube virtual machine and deploy Kubernetes into it.

Download https://kubernetes.io/docs/setup/minikube[minikube] and add it to your path.

[#setup-minikube-start]
[source,bash,subs="+macros,+attributes"]
----
$TUTORIAL_HOME/bin/start-minikube.sh
----
copyToClipboard::setup-minikube-start[]

.Minikube starting
[source,bash,subs="+macros,+attributes"]
----
❌  profile "{tutorial-namespace}" not found
✅  Created a new profile : {tutorial-namespace}
✅  minikube profile was successfully set to {tutorial-namespace}
😄  [{tutorial-namespace}] minikube v1.6.2 on Darwin 10.15.2
✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit])
🔥  Creating virtualbox VM (CPUs=4, Memory=8192MB, Disk=50000MB) ...
🐳  Preparing Kubernetes v1.14.0 on Docker '19.03.5' ...
    ▪ apiserver.enable-admission-plugins=LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook
🚜  Pulling images ...
🚀  Launching Kubernetes ...
⌛  Waiting for cluster to come online ...
🏄  Done! kubectl is now configured to use "{tutorial-namespace}"
----

**Navigate to registry helper folder:**

[#minikube-registry-helper-nav]
[source,bash,subs="attributes+,+macros"]
----
cd $TUTORIAL_HOME/apps/minikube-registry-helper
----
copyToClipboard::minikube-registry-helper-nav[]

**Deploy Registry Helper**

As part of some exercises in the tutorial, we need to push and pull images to local internal registry. To make push and pull smoother we will have a helper deployed so that we can use some common names like `dev.local`, `example.com` as registry aliases for internal registry

[#minikube-add-entry-to-host]
[source,bash,subs="attributes+,+macros"]
----
./configure.sh
----
copyToClipboard::minikube-add-entry-to-host[]

[IMPORTANT]
=====
Wait for the Daemonset to be running before proceeding to next step, the status of the Daemonset can be viewed via `kubectl get pods -n kube-system -w`, you can do kbd:[CTRL+c] to end the watch.
=====

A successful configure run will show the minikube node `/etc/hosts` file with the following entries:

[source,bash]
----
127.0.0.1       localhost
127.0.1.1 demo
10.111.151.121  example.com
10.111.151.121  example.org
10.111.151.121  test.com
10.111.151.121  test.org
----

[NOTE]
======
The IP for `test.com` and `example.com` will match the **CLUSTER-IP** of the internal registry. To know the Cluster IP run the command:

[#minikube-check-registry-ip]
[source,bash,subs="attributes+,+macros"]
----
kubectl get svc registry -n kube-system
----
copyToClipboard::minikube-check-registry-ip[]
======

[source,bash,subs="attributes+,+macros"]
----
NAME       TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
registry   ClusterIP   10.111.151.121   <none>        80/TCP                  178m
----


A successful patch will have the coredns updated ConfigMap `coredns` in `kube-system`

[source,yaml]
----
apiVersion: v1
data:
  Corefile: |-
    .:53 {
        errors
         rewrite name example.com  registry.kube-system.svc.cluster.local
    rewrite name example.org  registry.kube-system.svc.cluster.local
    rewrite name test.com  registry.kube-system.svc.cluster.local
    rewrite name test.org  registry.kube-system.svc.cluster.local

        health {
           lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
           pods insecure
           fallthrough in-addr.arpa ip6.arpa
           ttl 30
        }
        prometheus :9153
        forward . /etc/resolv.conf
        cache 30
        loop
        reload
        loadbalance
    }
kind: ConfigMap
metadata:
  name: coredns
----

[#deploy-tekton]
*Deploy Tekton Pipelines*

To deploy the Tekton pipelines:

[#tekton-deploy-pipelines]
[source,bash,subs="+macros,attributes+"]
----
kubectl apply --filename \
https://github.com/tektoncd/pipeline/releases/download/{tekton-version}/release.yaml
----
copyToClipboard::tekton-deploy-pipelines[]

[NOTE]
======
It will take few mins for the Tekton pipeline components to be installed, you an watch the status using the command:
[#watch-tekton-deploy]
[source,bash,subs="+macros,attributes+"]
----
kubectl get pods -n tekton-pipelines -w
----
copyToClipboard::watch-tekton-deploy[]

You can use kbd:[Ctrl+c] to terminate the watch
======

A successful deployment of Tekton pipelines will show the following pods:

[source,bash]
-----
NAME                                         READY   STATUS    RESTARTS   AGE
tekton-pipelines-controller-9b8cccff-j6hvr   1/1     Running   0          2m33s
tekton-pipelines-webhook-6fc9d4d9b6-kpkp7    1/1     Running   0          2m33s
-----

[#install-tekton-cli]
*Install Tekton CLI*
https://github.com/tektoncd/cli[Tekton CLI] is command line utility used to interact with the Tekton resources.

Download the Tekton cli and add to your path:

* https://github.com/tektoncd/cli/releases/download/v{tekton-cli-version}/tkn_{tekton-cli-version}_Darwin_x86_64.tar.gz[Download for macOS]

* https://github.com/tektoncd/cli/releases/download/v{tekton-cli-version}/tkn_{tekton-cli-version}_Linux_x86_64.tar.gz[Download for Linux]

* https://github.com/tektoncd/cli/releases/download/v{tekton-cli-version}/tkn_{tekton-cli-version}_Windows_x86_64.tar.gz[Download for Windows]

include::partial$tekton-cli.adoc[]
**Configuring Kubernetes namespace**

All the tutorial exercises will be deployed in namespace called `{tutorial-namespace}`:

[#setup-tekton-tutorial-ns]
[source,bash,subs="+macros,+attributes"]
----
kubectl create namespace {tutorial-namespace}
----
copyToClipboard::setup-tekton-tutorial-ns[]

[TIP]
=====
The https://github.com/ahmetb/kubens[kubens] utility installed as part of https://github.com/ahmetb/kubectx[kubectx] allows for easy switching between Kubernetes namespaces.

[#setup-tekton-tutorial-kubens]
[source,bash,subs="+macros,+attributes"]
----
kubens {tutorial-namespace}
----
copyToClipboard::setup-tekton-tutorial-kubens[]

=====

